# Generated by Django 3.0.2 on 2020-01-12 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0002_auto_20200112_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_delete',
            field=models.IntegerField(default=0),
        ),
    ]
